### PR TITLE
Fix Cannot read property replace of null

### PR DESCRIPTION
**Pull request by Erveon**

### CODE REVIEW

**Comment by iarna** [comment]
I've also added a test.

**Comment by Erveon** [comment]
Changes have been merged. Thank you.

**Comment by iarna** [comment]
Merged with https://github.com/npm/hosted-git-info/commit/c93148224547b0f541ca03bb706f196ae6e1f440 and landed in 2.7.1

**Comment by cdaringe** [comment]
nice! glad to find this!  was coming to see if someone hadn't already landed such a PR :)

**Pull request closed without merging**
