### PR TITLE
fix: http protocol use sshurl by default

### PR DESCRIPTION
**Pull request by fengmk2**

### CODE REVIEW

**Comment by fengmk2** [comment]
@isaacs This is a bug including by 2.8.0 version.

**Comment by fengmk2** [comment]
@isaacs 2.8.1 version still has this bug.

**Comment by isaacs** [comment]
Oh geez, that's dumb.  Good catch, thanks.  Fixed in 2.8.2.

**Comment by fengmk2** [comment]
@iarna 👍

**Pull request closed without merging**
