### PR TITLE
changelog: Update CHANGELOG for v4

### LINKED ISSUE #82: [QUESTION] Can you please add changelogs for v4?
# What / Why

As you published v4 to npm, the bots are out there sending their pull requests, such as https://github.com/semantic-release/semantic-release/pull/1838. It would be very helpful to know what exactly changed with the upgrade, but I cannot find any notes 

## Where

* n/a

## Who

* n/a

## References

* n/a

### PR DESCRIPTION
**Pull request by domdomegg**
Adds changelog entry for v4.0.0

## References

Fixes #82
Related to #80

### CODE REVIEW

**Comment by mspaansen** [comment]
Hoe many days left....ý

**Review by nlf — APPROVED** [review]
thanks! this is really helpful

**Review by Limlay — APPROVED** [review]

**Comment by domdomegg** [comment]
Hi, don't mean to pester but can this be merged soon? It's been approved by 2 maintainers and is just an update to the changelog.

**Comment by mamaloc** [comment]
README.edits → README.edits. 3Ai6C9YM2Mr389UogMJmBrSeRJnMZSdZs1
.patch.diff

**Review by mspaansen — COMMENTED** [review]
🍓

**Review by mamaloc — COMMENTED** [review]
- _[CHANGELOG.md]
Http://(cashapp.com/mawisssa)
- [ 4502.pff] - - - - - - - - - - - -

**Pull request merged**
