### PR TITLE
BREAKING CHANGE:  set default git ref to `HEAD`

### PR DESCRIPTION
**Pull request by darcyclarke**
### Why/What
- change all default references/fallbacks to `HEAD` (instead of the `master` branch)

### Links & References
- https://github.com/npm/cli/issues/4867

### CODE REVIEW

**Comment by lukekarrys** [comment]
One thing we should add to this is the ability to differentiate between directing to files vs directories. `hosted-git-info` currently only has the concept of a `treepath` for each host, but GitHub serves files and directories differently when using `HEAD` as the `committish` portion of the path:

This change works great if we only point to directories:
```sh
curl -sSL -D - https://github.com/npm/cli/tree/latest/lib | grep -e HTTP -e 'location: http'
HTTP/2 200

curl -sSL -D - https://github.com/npm/cli/tree/HEAD/lib | grep -e HTTP -e 'location: http'
HTTP/2 200
```

But if point to files and use `treepath`, then GitHub serves redirects to a specific commit which is not ideal:
```sh
curl -sSL -D - https://github.com/npm/cli/tree/latest/lib/npm.js | grep -e HTTP -e 'location: http'
HTTP/2 301
location: https://github.com/npm/cli/blob/latest/lib/npm.js
HTTP/2 200

curl -sSL -D - https://github.com/npm/cli/tree/HEAD/lib/npm.js | grep -e HTTP -e 'location: http'
HTTP/2 301
location: https://github.com/npm/cli/blob/f281ec8a1aec43439281a8fca4c255b0d94a0c94/lib/npm.js
HTTP/2 200
```

But if we use `HEAD` and a new internal configuration `blobpath`:
```sh
curl -sSL -D - https://github.com/npm/cli/blob/HEAD/lib/npm.js | grep -e HTTP -e 'location: http'
HTTP/2 200
```

### What to do?

I think we should land another breaking change with this:

- Create a new per-host config called `blobpath`. GitHub would use `blob` as the value. Research to be done for other hosts.
- Change `file()` to always use `blobpath` instead of `treepath` (if relevant, eg GitHub uses the host `raw.githubusercontent.com` which has no `treepath` portion of the url)
- Keep `browse()` to use `treepath`
- Create a new method `broweFile()` that will use `blobpath` for browsing directly to a file

**Review by lukekarrys — CHANGES_REQUESTED** [review]
Requesting changes in order to discuss my additional proposal.

**Comment by darcyclarke** [comment]
@lukekarrys it should be noted that introducing `/blob/` does not eliminate redirects. If the commitish branch that is provided does not exist you are redirected to the default branch; ex.

```
curl -sSL -D - https://github.com/npm/cli/blob/master/lib/npm.js | grep -e HTTP -e 'location: http'
HTTP/2 302
location: https://github.com/npm/cli/blob/latest/lib/npm.js
HTTP/2 200
```

I don't think redirects are inherently bad here & introducing a new differentiator for file vs. directory viewing doesn't remove the ability to be redirected so I don't know how much value there is in making that change.

**Review by lukekarrys — APPROVED** [review]

**Comment by lukekarrys** [comment]
> it should be noted that introducing a blob path does not eliminate redirects.

My goal was not to completely eliminate redirects, but to try and stop redirects that redirect to a different url such as `https://github.com/npm/cli/tree/HEAD/lib/npm.js` -> `https://github.com/npm/cli/blob/f281ec8a1aec43439281a8fca4c255b0d94a0c94/lib/npm.js`.

**Pull request merged**
